development:
  clients:
    default:
      database: amelia_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: amelia_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      database: amelia_production
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
